---
deployment:
  tasks:
    - echo "Deploy started: $(date)"

    # 1) wipe out old site (but keep .htaccess if you have one)
    - |
      find /home8/marriage/public_html \
        -maxdepth 1 -mindepth 1 \
        -not -name '.htaccess' \
        -exec rm -rf {} +

    # 2) copy everything from the git‐checked‐out directory 
    #    (i.e. the static build you’ll push into 'production')
    - cp -a . /home8/marriage/public_html/

    # 3) remove the manifest itself from your live dir
    - rm -f /home8/marriage/public_html/.cpanel.yml

    - echo "Deploy finished: $(date)"
